version: '3.5'

services:
  order-service:
    container_name: order-service2
    build:
      context: ./
      dockerfile: Dockerfile
    image: order-service2
    ports:
      - '${APP_PORT}:${APP_PORT}'
    environment:
      - SPRING_CLOUD_CONFIG_URI=${SPRING_CLOUD_CONFIG_URI}
    networks:
      - spring-microservice

networks:
  spring-microservice:
    external: true
