services:
  config-service:
    container_name: config-service
    build:
      context: .
      dockerfile: Dockerfile
    image: config-service
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src/main/resources/config/global.properties:/src/main/resources/config/global.properties
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=${EUREKA_CLIENT_REGISTER_WITH_EUREKA}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      - EUREKA_CLIENT_FETCH_REGISTRY=${EUREKA_CLIENT_FETCH_REGISTRY}
    networks:
      - spring-microservice

networks:
  spring-microservice:
    external: true
