version: '3.5'

services:
  order-service:
    container_name: order-service
    build:
      context: ./
      dockerfile: Dockerfile
    image: order-service
    ports:
      - '${APP_PORT}:${APP_PORT}'
    environment:
      # - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      # - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      # - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      # - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      # - EUREKA_CLIENT_REGISTER_WITH_EUREKA=${EUREKA_CLIENT_REGISTER_WITH_EUREKA}
      # - EUREKA_CLIENT_FETCH_REGISTRY=${EUREKA_CLIENT_FETCH_REGISTRY}
      - SPRING_CLOUD_CONFIG_URI=${SPRING_CLOUD_CONFIG_URI}
    networks:
      - spring-microservice

networks:
  spring-microservice:
    external: true
