services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - spring-microservice
volumes:
  redis-data:


networks:
  spring-microservice:
    external: true
