server:
  port: 8000

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

    discovery:
      client:
        simple:
          instances:
            order-service:
              - uri: http://order-service:8084
              - uri: http://order-service:8085

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url.defaultZone: http://eureka-server:8761/eureka/